# Generated by Django 3.2.16 on 2022-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='location',
        ),
        migrations.AddField(
            model_name='metric',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
